"""add_generic_billing_columns

Revision ID: 9c801a0a3a4a
Revises: 9e3a6f1d2c3b
Create Date: 2026-06-13 20:01:21.250231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c801a0a3a4a'
down_revision: Union[str, None] = '9e3a6f1d2c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('billing_provider', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('billing_customer_id', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('billing_subscription_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'organizations', ['billing_subscription_id'])
    op.create_unique_constraint(None, 'organizations', ['billing_customer_id'])
    # ### end Alembic commands ###
    
    # Backfill existing Stripe data to new generic billing columns
    op.execute(
        "UPDATE organizations SET billing_provider = 'stripe', "
        "billing_customer_id = stripe_customer_id, "
        "billing_subscription_id = stripe_subscription_id "
        "WHERE stripe_customer_id IS NOT NULL"
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'billing_subscription_id')
    op.drop_column('organizations', 'billing_customer_id')
    op.drop_column('organizations', 'billing_provider')
    # ### end Alembic commands ###
